### ISSUE TITLE
Get this up to date?

### ISSUE THREAD

**Issue by timspencer** [IMC3ofC/chef-provisioning-softlayer#1]
Hey there!  I tried to use this gem, but we are running a later version of chef than what your gem allows.  When I removed the constraint from the gem (and a few others, like the ancient chef-provisioning one), I get this:

```
[2015-09-16T10:48:46-07:00] DEBUG: OpenSSL::SSL::SSLError: machine[tspencer-slprovision-test1] (tspencer_test::ttest line 137) had an error: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
/Users/tspencer/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/net/http.rb:918:in `connect'
/Users/tspencer/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/net/http.rb:918:in `block in connect'
/Users/tspencer/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/Users/tspencer/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/net/http.rb:918:in `connect'
/Users/tspencer/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
/Users/tspencer/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/net/http.rb:857:in `start'
/Users/tspencer/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/xmlrpc/client.rb:472:in `do_rpc'
/Users/tspencer/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/xmlrpc/client.rb:279:in `call2'
/Users/tspencer/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/xmlrpc/client.rb:260:in `call'
/Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/softlayer_api-3.0.0/lib/softlayer/Service.rb:281:in `call_softlayer_api_with_params'
/Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/softlayer_api-3.0.0/lib/softlayer/Service.rb:210:in `method_missing'
/Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-provisioning-softlayer-3.1.9/lib/chef/provisioning/softlayer_driver/helpers/cache.rb:50:in `load_meta_data'
/Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-provisioning-softlayer-3.1.9/lib/chef/provisioning/softlayer_driver/driver.rb:70:in `initialize'
/Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-provisioning-softlayer-3.1.9/lib/chef/provisioning/softlayer_driver/driver.rb:41:in `new'
/Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-provisioning-softlayer-3.1.9/lib/chef/provisioning/softlayer_driver/driver.rb:41:in `from_url'
/Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-provisioning-1.3.0/lib/chef/provisioning.rb:86:in `driver_for_url'
/Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-provisioning-1.3.0/lib/chef/provisioning/chef_run_data.rb:103:in `driver_for_url'
/Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-provisioning-1.3.0/lib/chef/provisioning/chef_run_data.rb:84:in `driver_for'
/Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-provisioning-1.3.0/lib/chef/provider/machine.rb:103:in `new_driver'
/Users/tspencer/.rvm/gems/ruby-2.0.0-p451/gems/chef-provisioning-1.3.0/lib/chef/provider/machine.rb:24:in `block in <class:Machine>'
```

Not sure if that helps or not, but I wanted to register some interest in getting this code up to date, if possible.  Thanks, and have fun!

**Comment by wzymaster** [comment]
@timspencer  oh, it's a problem with OpenSSL::SSL::SSLError in your Rails app and probably you want to try a few links below : 

http://railsapps.github.io/openssl-certificate-verify-failed.html
http://stackoverflow.com/questions/12208110/opensslsslsslerror-certificate-verify-failed

**Comment by timspencer** [comment]
Yes.  I know what the error says.  That error is not emitted by a rails app, but by chef-client -z while trying to provision a node.  The problem is that I don't control softlayer's cert (which may or may not be properly set up), nor do I control the code that calls into net/http (which can be told to ignore ssl verification errors).  I was assuming that this was why you were constraining the chef and chef-provisioning gem versions.

My request still stands:  Can you update your constraints to modern versions of chef and chef-provisioning and make sure it works?  I'm willing to bet that you can do this a lot faster/easier than I can.  :-)

**Comment by wzymaster** [comment]
@timspencer sure, I will try to get some time this week to upgrade it.

**Comment by wzymaster** [comment]
@timspencer before the upgraded version is available, probably you want to restrict your gems in versions like below  :  

chef (11.16.4)
chef-provisioning (0.18)
chef-zero (2.2.1)
cheffish (0.9.2)

**Comment by boldandbusted** [comment]
Any progress here? I'd love to help - is there a TODO? :)

**Comment by wzymaster** [comment]
@boldandbusted sure, please feel free to make pull request and we can work together on this. Btw, I just updated this driver to 4.0 and will publish it very soon. Probably you can help from there.

**Comment by boldandbusted** [comment]
@wzymaster Wow, that was fast. Awesome! Do you mind if I also help a bit with the docs?

**Comment by wzymaster** [comment]
@boldandbusted Yes, for sure ! Please feel free to let me know what you want to do together.
